Repository Carbonable/carbonable-home, pull requests merged in 2022-11, with the labels that each got.

#37 feature(front): add links to legacy launchpad
  app/components/Home/Menu/Desktop.tsx
  app/components/Home/Menu/Mobile.tsx
  app/components/Home/Section/Title.tsx
  app/styles/app.css
  app/utils/links.ts
Labels: Type: Feature, Readiness: Ready for dev, Component: Frontend, Complexity: Obvious

#36 Feature/refect yield simulator
  app/components/Home/Section/Carousel.tsx
  app/components/Home/Section/Simulator/Kpi.tsx
  app/components/Home/Section/Simulator/OffsetSimulator.tsx
  app/components/Home/Section/Simulator/YieldSimulator.tsx
  app/components/Home/Section/Simulators.tsx
  app/routes/index.tsx
  app/routes/simulators/analytics.tsx
  app/styles/app.css
  app/utils/simulator.server.ts
  app/utils/utils.ts
  styles/app.css
  tailwind.config.js
Labels: Type: Feature, Readiness: Ready for dev, Component: Frontend, Complexity: Complex, Epic: Website Homepage

#38 Feature/homepage refact manifesto
  app/components/Home/Menu/Menu.tsx
  app/components/Home/Section/B2B.tsx
  app/components/Home/Section/Carousel.tsx
  app/components/Home/Section/Partners.tsx
  app/components/Home/Section/Simulators.tsx
  app/components/Home/Section/Steps.tsx
  app/components/Home/Section/Title.tsx
  app/components/Home/Section/Values.tsx
  app/components/Home/Section/Video.tsx
  app/routes/index.tsx
  app/styles/app.css
  package-lock.json
  package.json
  public/assets/images/home/manifesto-logo.png
  styles/app.css
  tailwind.config.js
Labels: Type: Feature, Component: Frontend, Epic: Website Homepage

#42 feature(front): Add animation from Lord. Change configuration for fly…
  app/components/Home/Section/Carousel.tsx
  app/components/Home/Section/Simulator/YieldSimulator.tsx
  app/components/Home/Section/Title.tsx
  app/components/Home/Section/Values.tsx
  app/components/Home/Section/Video.tsx
  app/components/Image/index.tsx
  app/root.tsx
  app/routes/index.tsx
  app/routes/launchpad.tsx
  app/styles/app.css
  app/utils/links.ts
  app/utils/scrollingFunctions.ts
  app/utils/starknetId.ts
  fly-env/fly_carbonable-home.toml
  fly.toml
  package-lock.json
  package.json
  prisma/seed.ts
  styles/app.css
  tsconfig.json
Labels: Type: Feature, Component: Frontend, Epic: Website Homepage

#43 update-manfesto
  app/components/Home/Section/Values.tsx
  app/routes/index.tsx
  app/styles/app.css
Labels: Component: UI/UX, Component: Frontend, Complexity: Obvious, Epic: Website Homepage

#46 update/B2B-placeholder
  app/components/Home/Section/B2B.tsx
  public/assets/images/home/b2b-placeholder2.png
Labels: Component: UI/UX, Component: Frontend, Complexity: Obvious, Epic: Website Homepage

#48 devops: carbonable_home has its own database
  README.md
  package-lock.json
  package.json
  prisma/migrations/20221005144926_init/migration.sql
  prisma/migrations/20221128091152_init/migration.sql
  tsconfig.json
Labels: Type: Security, Component: DevOps, Readiness: Approved, Complexity: Obvious, Epic: Website Homepage
